              name: Setup Java JDK
                uses: actions/setup-java@v4.2.1
                steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'zulu' # See 'Supported distributions' for available options
    java-version: '21'
- run: java HelloWorldApp.java
            
